name: Go

on:
  push:
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24", "1.25"]
    steps:
      - name: Updating ...
        run: sudo apt-get -qq update

      - uses: actions/checkout@v5

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Go build (source)
        run: go build

      - name: Go vet
        run: go vet -v ./...